# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b071a4afc551c5231415bfb4902ffb858126d5b31982088cc33f1291bb6859281aceee99cee56d90f5d4b4f7860ec175b1ced7b2aa1753f69caae55b9c44f0cb

test:
  secret_key_base: ca506f85a4a1b45f77a7e0255c108618ccf32b3368672c5daec656d8e3654288348a58509e2fb690fa53be5619e5a1581b622e5da6cbbe0968d64c29b3cab03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
